### ISSUE TITLE
mariadb fails to start

### ISSUE THREAD

**Issue by depasseg** [cloudera/cloudera-playbook#10]
On a centos 7.4 system, the /roles/mariadb/tasks/main.yml fails when trying to start mariadb after successfully creating the configuration file, the log file and PID directory.

A manual yum install of mariadb-server works fine.

Logs attached:
[logs.txt](https://github.com/cloudera/cloudera-playbook/files/1641416/logs.txt)
[job_35.txt](https://github.com/cloudera/cloudera-playbook/files/1641404/job_35.txt)

**Comment by depasseg** [comment]
I used [this ](https://github.com/bertvv/ansible-role-mariadb)to install mariadb to that host, and then cloudera installation continued to run.

**Comment by VladimirNovgorodov** [comment]
a buffer of innodb_buffer_pool_size=... has a size comparable to host memory?

**Comment by kuldeepkulkarni09** [comment]
@depasseg - Please check if selinux is disabled, I was able to resolve this issue after disabling selinux.

**Comment by lhoss** [comment]
> I was able to resolve this issue after disabling selinux.

Same for me, works after setting it permissive ( `setenforce 0`).
A check in the audit shows that somehow there seems a permission problem with the `/var/log/mysqld.log`:
```
grep mysql /var/log/audit/audit.log
```
Same info here:https://dba.stackexchange.com/questions/86129/could-not-start-mysql-or-mariadb-permissions-were-ok-but-mysql-bin-index-permi#136591
Still wondering why exactly?!

---

> I used [this ](https://github.com/bertvv/ansible-role-mariadb)to install mariadb to that host, and then cloudera installation continued to run.

That [ansible-role-mariadb ](https://github.com/bertvv/ansible-role-mariadb) role looks like a good choice , allowing fully customized config.
The mariadb deployment (builtin cloudera role) writes a lot of the configs hardcoded .. and is IMO *missing* >1 important setting, so the mysqld listens on *all* interfaces:
```
bind-address=*
```
More infos, 1.cfg option shown in https://github.com/bertvv/ansible-role-mariadb#basic-configuration

**Comment by dbeech** [comment]
Closing as stale. @depasseg please re-open if you still need to discuss your issue.
