### ISSUE TITLE
MariaDB fails to start after restarting the server

### ISSUE THREAD

**Issue by rafaelarana** [cloudera/cloudera-playbook#11]
Although on first installation it starts OK, after restarting the server it assumes that  mysql_pid_file dir will be at  /var/run/mariadb instead of the one declared in the template.

**Comment by lhoss** [comment]
Fix PR  #12 by @rafaelarana 

Edit:
For me restarting mariadb (v5.5.60 on centos7) also works *without* the proposed fix.
Not sure why @rafaelarana needed the change
