### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: No module named cm_api.api_client

### ISSUE THREAD

**Issue by hskundhal** [cloudera/cloudera-playbook#15]
Error received in installing  5.14.0.
Command works fine locally.
 TASK [scm : Install CM Python API Client]

**Comment by plartemyev** [comment]
Hi! It's happening, because action_plugins/scm_hosts.py is executed on the host where you invoked ansible-playbook, so you should install cm-api there too.

**Comment by lhoss** [comment]
> so you should install cm-api ...on the host where you invoked ansible-playbook [the controller node]

following 1-line fix will ensure that the cm-api gets (only) installed there [on the controller node], but ensure you run your playbook as root or user with passwordless sudo (else the install will fail): 
 https://github.com/cloudera/cloudera-playbook/compare/master...ramencloud:local-cm-api

**Comment by dbeech** [comment]
Closed as merged PR #51 removes the need for the CM API module to be installed at all.
