### ISSUE TITLE
Update this repo with fixes made by other contributors 

### ISSUE THREAD

**Issue by ricardogaspar2** [cloudera/cloudera-playbook#18]
Hi, this repo has been very stale and I see that other contributors have forked this project and made some valuable changes. Would you be able to aggregate those changes and update this repository in order to have a more central and trustworthy repository to look for. 

Thanks in advance! ;)

**Comment by technmsg** [comment]
The steps to contribute look like this:

- fork
- commit
- submit a pull request
- complete an ICLA or CCLA

**Comment by lhoss** [comment]
Good to see, that the last 2 month there is action again here !
It would be great to clean/close some of the 15 issues also 👍 
( ps: I'm new here, but motivated to bring my ansible experience to this community too. See also https://github.com/cloudera/cloudera-playbook/issues/21#issuecomment-489639618

**Comment by roczei** [comment]
Hi @ricardogaspar2 and @lhoss,

You need to first sign and return an ICLA and CCLA before we can accept and redistribute your contribution. Once these are submitted you are free to start contributing to cloudera-playbook. Submit these to CLA@cloudera.com

Here you can find the pdf files:

https://github.com/cloudera/cloudera-playbook/tree/master/icla

Please update this issue (18) if you receive the confirmation from our CLA team.

Thank you!

**Comment by dbeech** [comment]
I'm closing this issue since I have recently taken over as maintainer of this repo and will be actively reviewing and merging improvements. Please send us your PRs!
