### ISSUE TITLE
Running script without license keys

### ISSUE THREAD

**Issue by asimsoroya** [cloudera/cloudera-playbook#19]
Hi I am setting up cluster without license, I managed to run the script though found few issues in the script. Will share the details, I removed some lines of code from script to run without license as those modules were included in script like advanced reporting, 
Can any body suggest what changes need to be made to run the script without license or free mode

**Comment by lhoss** [comment]
Hi @asimsoroya 
Details would be appreciated, as many more people (me too) want to deploy (initially) without a license 👍 
( Else I'll probably need to fix this myself )

**Comment by dbeech** [comment]
Closing. No license is required to run the playbook -- CM will automatically start with enterprise trial license if no license file is provided. If you would prefer to run the free version (Cloudera Express) then you can cancel the trial through the CM interface. 

@asimsoroya please re-open if you still want to discuss your issue.
