### ISSUE TITLE
error on tmp/scm.json file 

### ISSUE THREAD

**Issue by asimsoroya** [cloudera/cloudera-playbook#20]
I get error on temp file, when I switch value in ansible.cfg value of pipelining the error goes away and come back not sure why?
************************************************************************************************************************************************************
fatal: [cloudmanager.ee-hadoop.com.au]: FAILED! => {"msg": "Failed to get information on remote file (/home/hadoop/tmp/scm.json): Sorry, try again.\n[sudo via ansible, key=bkfkxloiefebvjjruekluqqrpzaeymwo] password: \nsudo: 1 incorrect password attempt\n"}

**Comment by dbeech** [comment]
Closing as fixed by #28.
