### ISSUE TITLE
Running script for latest version of cloudera

### ISSUE THREAD

**Issue by asimsoroya** [cloudera/cloudera-playbook#21]
Hi,
Can I know any one have experience of running the script on latest version of cloudera.
THanks

**Comment by lhoss** [comment]
Hi
I am new here, but bringing a broad ansible experience, especially related to HWX HDP deployments (also contributor to https://github.com/hortonworks/ansible-hortonworks ) 

My plan is (also) to deploy the latest CDH 6.x and will find out if it's already supported, or else I'ld be happy to contribute a PR to support deployment for at least the latest 2 major CDH versions (5.x , 6.x)
If anybody has done that already, would be great to share 👍 

Edit: Work for this started with PR https://github.com/cloudera/cloudera-playbook/pull/23

**Comment by lhoss** [comment]
This issue is *solved* by https://github.com/cloudera/cloudera-playbook/pull/26
@roczei you can close it
fyi @asimsoroya
