### ISSUE TITLE
keep getting "invalid role mapping HDFS-HTTPFS-1" for "import cluster template task" when running ansible playbook role

### ISSUE THREAD

**Issue by asimzafar202** [cloudera/cloudera-playbook#47]
```fatal: [52.61.239.57]: FAILED! => {"changed": false, "connection": "close", "content": "{\n  \"message\" : \"Invalid role mapping for HDFS-HTTPFS-1. No role group configuration of type HTTPFS is present in the host template HostTemplate-Gateway.\"\n}", "content_type": "application/json;charset=utf-8", "date": "Mon, 30 Sep 2019 21:06:45 GMT", "elapsed": 0, "expires": "Thu, 01 Jan 1970 00:00:00 GMT", "json": {"message": "Invalid role mapping for HDFS-HTTPFS-1. No role group configuration of type HTTPFS is present in the host template HostTemplate-Gateway."}, "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "redirected": false, "set_cookie": "CLOUDERA_MANAGER_SESSIONID=node07hsc8tsx0kuffp3j6ziceh437.node0;Path=/;HttpOnly", "status": 400, "url": "http://52.61.239.57:7180/api/v33/cm/importClusterTemplate?addRepositories=true", "x_content_type_options": "nosniff", "x_frame_options": "DENY", "x_xss_protection": "1; mode=block"}```

**Comment by ciucanu** [comment]
Same here, I manually add it.

**Comment by asimzafar202** [comment]
Did you manually add hosts to cluster through the UI? or you manually created the json template thats being posted to the API?

**Comment by dbeech** [comment]
Hi @asimzafar202. Can you post your inventory file for me to check? 

Basically, whichever group has `HDFS-1-HTTPFS-BASE` in the host template file (roles/cdh/templates/host.j2) also needs a corresponding `role_ref_names=HDFS-HTTPFS-1` variable declared in the inventory file. 

For example: 
```
}, {
  "refName": "HostTemplate-Edge",
  "cardinality": 1,
  "roleConfigGroupsRefNames": [
    "HDFS-1-HTTPFS-BASE",
...
```
... also needs ...
```
[edge_servers]
edge.example.com        host_template=HostTemplate-Edge    role_ref_names=HDFS-HTTPFS-1
```

This is a little annoying and I'd like to find a way around it, but I suspect it is a limitation of the Cloudera Manager cluster templates feature.

**Comment by asimzafar202** [comment]
```
[scm_server]
10.2.19.7

[db_server]
10.2.19.9

[utility_servers:children]
scm_server
db_server

[gateway_servers]
10.2.19.5        host_template=HostTemplate-Gateway        role_ref_names=HDFS-HTTPFS-1

[master_servers]
10.2.19.8        host_template=HostTemplate-Master1
10.2.19.12        host_template=HostTemplate-Master2
10.2.19.11        host_template=HostTemplate-Master3

[worker_servers]
10.2.19.6
10.2.19.14
10.2.19.13

[worker_servers:vars]
host_template=HostTemplate-Workers

[cdh_servers:children]
utility_servers
gateway_servers
master_servers
worker_servers

[all:vars]
ansible_user=ec2-user
```

**Comment by dbeech** [comment]
Thank you. So, if you do not want HTTPFS and you do not have a line for `HDFS-1-HTTPFS-BASE` in the file `roles/cdh/templates/host.j2` then it is safe to delete the variable `role_ref_names=HDFS-HTTPFS-1` from your inventory. 

Or - if you do actually want an HTTPFS role, then you need to make sure it is added to the correct section of the host template, i.e. `HostTemplate-Gateway` and not `HostTemplate-Edge` or elsewhere.

**Comment by dbeech** [comment]
[This commit](https://github.com/cloudera/cloudera-playbook/commit/b72540230386598b2b3f08920c3187613e8f922b) probably broke your playbook, when I introduced a new edge node template and moved some things around. Apologies :(

**Comment by asimzafar202** [comment]
No worries. I tried it with the edge server and it wasn't working either. Also nothing is getting installed on the edge server by the roles.. Didn't understand the usage for it

**Comment by dbeech** [comment]
In your case what would (probably) work is to replace the following in your inventory file. 

Replace:
```
[gateway_servers]
10.2.19.5        host_template=HostTemplate-Gateway        role_ref_names=HDFS-HTTPFS-1
```
with
```
[edge_servers]
10.2.19.5        host_template=HostTemplate-Edge        role_ref_names=HDFS-HTTPFS-1
```

**Comment by asimzafar202** [comment]
When removing the HDFS-1-HTTPFS-BASE I still received an error. The role is still present in hdfs.j2 template. What should I remove from that file if I do not want HTTPFS?

**Comment by dbeech** [comment]
From hdfs.j2 remove the lines 94-98
```
      "refName": "HDFS-1-HTTPFS-BASE",
      "roleType": "HTTPFS",
      "configs": [],
      "base": true
    }, {
```
and lines 120-126
```
  "roles": [
    {
      "refName": "HDFS-HTTPFS-1",
      "roleType": "HTTPFS"
    }
  ]
```
Then delete the comma from line 119 so that the syntax is correct.

**Comment by asimzafar202** [comment]
Thanks a lot! Adding the  HDFS-1-HTTPFS-BASE to the HostTemplate-Gateway and removing the HostTemplate-Edge group completely worked for me. I am also trying out removing HTTPFS completely to see if that works as well. Thanks again for the quick response!

**Comment by Data-drone** [comment]
FYI in the current master version there is also an entry for HTTPFS under `hue.j2` as well that needs deleting if removing it

**Comment by DFK-Vienna** [comment]
My solution to this problem was to combine the Edge Server and the Gateway server onto the same computer.
It seems the edge server is not included into the 'cdh_servers'

So I propose two solutions:

* Add edge_servers to cdh_servers:children
* Combine edge_servers-Hardware with one of the cdh_servers (in my case it was the gateway server)
