### ISSUE TITLE
New Project, Ansible deployment

### ISSUE THREAD

**Issue by VickyRPrajapati** [cloudera/cloudera-playbook#52]
Hi,

I have created a new ansible script for multi-note deployment and configuration of CDH. I want to publish this is this or a related repository. What are the steps to do this?

Thanks,

Vicky

**Comment by dbeech** [comment]
HI @VickyRPrajapati - not sure I understand fully. Have you written a patch for this repository or a brand new ansible script (playbook) ?

If it's a patch, then please open a pull request and we will review. Some guidance on pull requests can be found here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests. Thanks!

**Comment by VickyRPrajapati** [comment]
Hi DBeech, 
It is not patch of existing ansible script. it is new script for installation of Cloudera.
Thanks.

**Comment by dbeech** [comment]
Ok, then in that case I can only suggest to host your scripts on a personal repository. If you have any specific features in your version that do not exist in the Cloudera playbook here, then please create new issue tickets and we can look at porting some code across as patches. 

I will close this issue for now. Please re-open if you want to discuss further - thanks!
