### ISSUE TITLE
Dynamic inventory script for CM does not work with Python 3

### ISSUE THREAD

**Issue by dbeech** [cloudera/cloudera-playbook#55]
@roczei could you please take a look when you have time? Otherwise I will try to fix when I get a chance.

**Comment by roczei** [comment]
Hi @dbeech,

Ok, I am going to fix it this month (November 2019).

**Comment by roczei** [comment]
Hi @dbeech,

Done. This was an incompatible change therefore I created a new file for Python 3 and renamed the original one to reflect that it is for Python 2.

Python 2 version: cloudera-playbook/dynamic_inventory_cm_py2
Python 3 version: cloudera-playbook/dynamic_inventory_cm_py3

[Here](https://github.com/cloudera/cloudera-playbook/commit/01ff961f8741c31a56bc0f189f987f697bd89726) is the related commit.

**Comment by dbeech** [comment]
Thanks for the quick turnaround @roczei
