### ISSUE TITLE
No service type 'SENTRY' available for cluster with version 'CDH 7.0.3'

### ISSUE THREAD

**Issue by mridul0709** [cloudera/cloudera-playbook#66]
Hi I am trying to install cdp 7.0.3 using this playbook and I have managed to install it. The second last step of play "**Import cluster template**" didn't run successfully and it failed with error below. Could someone help me here please

>  java.lang.IllegalArgumentException: No service type 'SENTRY' available for cluster with version 'CDH 7.0.3'.

**Comment by Jimvin** [comment]
Apache Sentry is not part of CDP 7.0.3 as it was replaced by Apache Ranger, so the error that you are seeing is valid. You need to update your configuration to define a cluster with valid list of services.

**Comment by mridul0709** [comment]
Perfect, thank you for the answer. It worked after commenting sentry service from cdh_servers.yml.
