### ISSUE TITLE
5 PRs lost during PR #40 force-push merged 2019-08-30. Let's bring'em back!

### ISSUE THREAD

**Issue by lhoss** [cloudera/cloudera-playbook#68]
As already mentioned in  https://github.com/cloudera/cloudera-playbook/pull/40#issuecomment-656603063
I detected a number of former PR/fixes, that were not anymore in master (since too long)

I identified 5 LOST PRs, by looking at:
https://github.com/cloudera/cloudera-playbook/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc
(and analyzing the code)
https://github.com/cloudera/cloudera-playbook/pull/25, merged 20190827, 11h48
https://github.com/cloudera/cloudera-playbook/pull/28, merged 20190827, 11h58
https://github.com/cloudera/cloudera-playbook/pull/37, merged 20190828, 10h49
https://github.com/cloudera/cloudera-playbook/pull/38, merged 20190829, 19h14
https://github.com/cloudera/cloudera-playbook/pull/39, merged 20190830, 11h56

---
Today I'll focus on bringing back https://github.com/cloudera/cloudera-playbook/pull/28, which contains critical fixes required for an install happening today at one customer where imstall runs from AWX/Tower
In can also work on brining back the useful changes from PRs 37-39 (all by @dbeech ), if @dbeech has no time

**Comment by dbeech** [comment]
wow, yeah -  i can't even remember doing the force push. that was bad, apologies.
I've just merged #28 and if you want to raise PRs for the others I'll merge these again too if needed urgently. I won't have time to work on this for a while.

**Comment by lhoss** [comment]
Thanks!
ps: I went through the list, to check if anything else was to 'restore', but NO. So all good now!
* PRs #37, #38 changes survived (checked via cherry-pick'ing PR commits, and looking at the conflicting diffs)
* PR #39 commits also (all in master)
Except #25 change is missing, but it's not worth redoing a PR , for this 1line comment removal
closing this
