### ISSUE TITLE
Need help in running the playbook

### ISSUE THREAD

**Issue by smahalingam** [cloudera/cloudera-playbook#8]
Hi, I see following error while running the playbook. 
"msg": "No hosts defined in SCM"

It's fails in the,
- name: Get SCM hostIds for inventory hosts
  action:  scm_hosts
  register: scm_hosts_result

I tried looking at the scm_hosts.py under action_plugin but no luck. Can someone help on this pls ?

**Comment by dbeech** [comment]
Closing as stale. @smahalingam please re-open if you still need to discuss your issue.
